import type { POI } from './mvpTypes';

const importedAt = '2026-05-26T00:00:00.000Z';

export const seedPois: POI[] = [
  {
    id: 'poi-cafe-olimpico',
    cityId: 'montreal',
    name: 'Cafe Olimpico',
    category: 'cafes',
    coordinate: { lat: 45.5238, lng: -73.6012 },
    source: 'curated',
    moods: ['coffee', 'energetic'],
    interestTags: ['cafes', 'architecture'],
    computedRouteValue: 82,
    curatedRouteValue: 94,
    openingHours: 'morning / afternoon',
    metadata: { neighborhood: 'Mile End' },
    lastImportedAt: importedAt,
  },
  {
    id: 'poi-la-fontaine',
    cityId: 'montreal',
    name: 'Parc La Fontaine',
    category: 'parks',
    coordinate: { lat: 45.5273, lng: -73.5704 },
    source: 'osm-seed',
    moods: ['calm', 'green', 'scenic'],
    interestTags: ['parks', 'viewpoints'],
    computedRouteValue: 88,
    lastImportedAt: importedAt,
  },
  {
    id: 'poi-mount-royal-lookout',
    cityId: 'montreal',
    name: 'Belvedere Kondiaronk',
    category: 'viewpoints',
    coordinate: { lat: 45.5036, lng: -73.5871 },
    source: 'osm-seed',
    moods: ['scenic', 'green'],
    interestTags: ['viewpoints', 'parks'],
    computedRouteValue: 91,
    lastImportedAt: importedAt,
  },
  {
    id: 'poi-notre-dame',
    cityId: 'montreal',
    name: 'Notre-Dame Basilica',
    category: 'churches',
    coordinate: { lat: 45.5045, lng: -73.5561 },
    source: 'osm-seed',
    moods: ['historic'],
    interestTags: ['churches', 'architecture'],
    computedRouteValue: 90,
    lastImportedAt: importedAt,
  },
  {
    id: 'poi-old-port',
    cityId: 'montreal',
    name: 'Old Port waterfront',
    category: 'waterfront',
    coordinate: { lat: 45.5057, lng: -73.5515 },
    source: 'osm-seed',
    moods: ['scenic', 'energetic'],
    interestTags: ['waterfront', 'viewpoints'],
    computedRouteValue: 84,
    lastImportedAt: importedAt,
  },
  {
    id: 'poi-verdun-beach',
    cityId: 'montreal',
    name: 'Verdun waterfront',
    category: 'waterfront',
    coordinate: { lat: 45.4594, lng: -73.5721 },
    source: 'osm-seed',
    moods: ['scenic', 'green', 'calm'],
    interestTags: ['waterfront', 'parks'],
    computedRouteValue: 86,
    lastImportedAt: importedAt,
  },
  {
    id: 'poi-westmount-park',
    cityId: 'montreal',
    name: 'Westmount Park',
    category: 'parks',
    coordinate: { lat: 45.4864, lng: -73.5992 },
    source: 'osm-seed',
    moods: ['calm', 'green'],
    interestTags: ['parks', 'architecture'],
    computedRouteValue: 79,
    lastImportedAt: importedAt,
  },
  {
    id: 'poi-atwater-market',
    cityId: 'montreal',
    name: 'Atwater Market',
    category: 'architecture',
    coordinate: { lat: 45.4808, lng: -73.5772 },
    source: 'osm-seed',
    moods: ['energetic', 'coffee'],
    interestTags: ['architecture', 'cafes', 'waterfront'],
    computedRouteValue: 81,
    lastImportedAt: importedAt,
  },
  {
    id: 'poi-public-toilet-mont-royal',
    cityId: 'montreal',
    name: 'Mont-Royal public toilets',
    category: 'public-toilets',
    coordinate: { lat: 45.5142, lng: -73.5879 },
    source: 'osm-seed',
    moods: ['calm', 'green'],
    interestTags: ['public-toilets', 'parks'],
    computedRouteValue: 55,
    lastImportedAt: importedAt,
  },
  {
    id: 'poi-metro-laurier',
    cityId: 'montreal',
    name: 'Laurier metro access',
    category: 'transit',
    coordinate: { lat: 45.5272, lng: -73.5897 },
    source: 'osm-seed',
    moods: ['calm', 'coffee'],
    interestTags: ['transit', 'cafes'],
    computedRouteValue: 60,
    lastImportedAt: importedAt,
  },
  {
    id: 'poi-square-st-louis',
    cityId: 'montreal',
    name: 'Square Saint-Louis',
    category: 'architecture',
    coordinate: { lat: 45.5174, lng: -73.5694 },
    source: 'curated',
    moods: ['historic', 'calm'],
    interestTags: ['architecture', 'parks'],
    computedRouteValue: 83,
    curatedRouteValue: 88,
    lastImportedAt: importedAt,
  },
  {
    id: 'poi-lachine-canal',
    cityId: 'montreal',
    name: 'Lachine Canal path',
    category: 'waterfront',
    coordinate: { lat: 45.4856, lng: -73.5728 },
    source: 'osm-seed',
    moods: ['scenic', 'energetic'],
    interestTags: ['waterfront', 'parks'],
    computedRouteValue: 85,
    lastImportedAt: importedAt,
  },
];
