import type { AccessibilityNote, Place, SafetyNote, Source } from "@/lib/types";
import { createGeneratedFallbackMedia, getMediaAssetsForPlace } from "@/lib/media/media-manifest";

type PlaceInput = Omit<Place, "accessibilityNotes" | "contentStatus" | "media" | "safetyNotes" | "sources">;

const sourcePlaceholder: Source = {
  id: "source-montreal-curation-placeholder",
  label: "Meaningful Routes editorial review",
  type: "placeholder",
  notes: "Reviewed against editorial notes, public place references, and walking-route context.",
  status: "placeholder"
};

const defaultAccessibilityNotes: AccessibilityNote[] = [
  {
    id: "place-access-sidewalks",
    label: "Sidewalk access varies",
    description: "Review curb cuts, surface condition, and entrances before marking this place field-ready.",
    severity: "info"
  }
];

const defaultSafetyNotes: SafetyNote[] = [
  {
    id: "place-safety-urban-crossings",
    label: "Urban crossings nearby",
    description: "Use marked crossings and check current construction or closures before relying on this stop.",
    severity: "info"
  }
];

const basePlaces: PlaceInput[] = [
  {
    id: "place-darmes",
    slug: "place-darmes",
    cityId: "montreal",
    name: "Place d'Armes",
    category: "square",
    area: "Old Montreal",
    coordinates: { lat: 45.5045, lng: -73.5561 },
    shortDescription: "A historic square framed by some of Montreal's most important civic and religious buildings.",
    story: "Place d'Armes is one of the clearest places to read Montreal's layers at street level: religious power, banking ambition, colonial memory, and modern civic life all face the same square.",
    whyItMatters: "It anchors Old Montreal and makes the city's architectural timeline visible in one compact place.",
    whatToNotice: ["Notre-Dame Basilica's Gothic Revival facade", "the Maisonneuve monument", "the contrast between stone banks and newer towers"],
    practicalInfo: ["Best early in the morning before tour groups arrive", "Benches and wide paved areas are available"],
    periodOrStyle: "Colonial, Gothic Revival, Beaux-Arts",
    tags: ["history", "architecture", "square", "old streets"],
    relatedRouteSlugs: ["old-montreal-monuments-loop", "place-darmes-circuit", "churches-courtyards-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "notre-dame-basilica",
    slug: "notre-dame-basilica",
    cityId: "montreal",
    name: "Notre-Dame Basilica",
    category: "church",
    area: "Old Montreal",
    coordinates: { lat: 45.5046, lng: -73.5564 },
    shortDescription: "A landmark Gothic Revival basilica facing Place d'Armes.",
    story: "The basilica gives Old Montreal its most recognizable silhouette and remains a compact lesson in craft, ornament, religious history, and public ceremony.",
    whyItMatters: "It is one of the strongest architectural anchors for first-time visitors exploring Old Montreal on foot.",
    whatToNotice: ["twin towers", "deeply carved stone details", "how the facade frames the square"],
    practicalInfo: ["Exterior viewing is easy from the square", "Interior visits may require timed entry"],
    periodOrStyle: "Gothic Revival",
    tags: ["churches", "architecture", "history"],
    relatedRouteSlugs: ["old-montreal-monuments-loop", "place-darmes-circuit", "churches-courtyards-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "pointe-a-calliere",
    slug: "pointe-a-calliere",
    cityId: "montreal",
    name: "Pointe-a-Calliere",
    category: "museum",
    area: "Old Montreal",
    coordinates: { lat: 45.5012, lng: -73.5546 },
    shortDescription: "An archaeology and history museum at the birthplace of Montreal.",
    story: "The site connects the contemporary museum with archaeological traces under the city, making it one of the best stops for understanding why this riverfront mattered.",
    whyItMatters: "It grounds Montreal's origin story in archaeology, river trade, and the earliest urban layers of the old city.",
    whatToNotice: ["modern museum massing", "riverfront position", "historic street alignment"],
    practicalInfo: ["Good indoor backup on rainy days", "Nearby streets can be uneven"],
    periodOrStyle: "Contemporary museum over archaeological site",
    tags: ["history", "museums", "waterfront"],
    relatedRouteSlugs: ["old-montreal-monuments-loop", "architecture-river-views"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "bonsecours-market",
    slug: "bonsecours-market",
    cityId: "montreal",
    name: "Bonsecours Market",
    category: "historic_building",
    area: "Old Montreal",
    coordinates: { lat: 45.5091, lng: -73.5525 },
    shortDescription: "A domed 19th-century market building near the Old Port.",
    story: "Bonsecours Market turns the waterfront into a civic stage, linking commerce, public life, and the river-facing identity of the old city.",
    whyItMatters: "Its dome is one of the Old Port's clearest orientation landmarks and a reminder of the waterfront's civic role.",
    whatToNotice: ["silver dome", "long market facade", "views back toward the river"],
    practicalInfo: ["Useful shelter nearby in poor weather", "The area can be busy on weekends"],
    periodOrStyle: "Neoclassical",
    tags: ["history", "architecture", "waterfront"],
    relatedRouteSlugs: ["old-montreal-monuments-loop", "old-port-foundries-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "place-jacques-cartier",
    slug: "place-jacques-cartier",
    cityId: "montreal",
    name: "Place Jacques-Cartier",
    category: "square",
    area: "Old Montreal",
    coordinates: { lat: 45.5085, lng: -73.5539 },
    shortDescription: "A sloping public square connecting Old Montreal streets with the Old Port.",
    story: "This is one of the neighborhood's most social spaces, where street life, terraces, and civic buildings compress into a short walk.",
    whyItMatters: "It shows the everyday public life side of Old Montreal beyond landmark facades.",
    whatToNotice: ["the gentle slope toward the port", "street performers and terraces", "views toward City Hall"],
    practicalInfo: ["Can be crowded in peak season", "Good rest stop with nearby cafes"],
    tags: ["history", "cafes", "old streets"],
    relatedRouteSlugs: ["old-montreal-monuments-loop", "old-port-foundries-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "montreal-city-hall",
    slug: "montreal-city-hall",
    cityId: "montreal",
    name: "Montreal City Hall",
    category: "historic_building",
    area: "Old Montreal",
    coordinates: { lat: 45.5084, lng: -73.5544 },
    shortDescription: "A Second Empire civic landmark facing the old city's public squares.",
    story: "City Hall links ceremonial architecture with the politics and public identity of Montreal.",
    whyItMatters: "It adds civic history to Old Montreal's stronger-known churches, markets, and waterfront spaces.",
    whatToNotice: ["mansard roofline", "ceremonial symmetry", "public square relationship"],
    practicalInfo: ["Exterior viewing is easiest from Place Jacques-Cartier", "Check access before planning an interior stop"],
    periodOrStyle: "Second Empire",
    tags: ["history", "architecture", "civic"],
    relatedRouteSlugs: ["old-montreal-monuments-loop"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "crew-collective-cafe",
    slug: "crew-collective-cafe",
    cityId: "montreal",
    name: "Crew Collective & Cafe",
    category: "cafe",
    area: "Old Montreal",
    coordinates: { lat: 45.5019, lng: -73.5602 },
    shortDescription: "A dramatic cafe and work hall inside a former bank interior.",
    story: "This stop turns a coffee break into an architectural reveal, where banking-era grandeur becomes a social interior.",
    whyItMatters: "It is one of the clearest examples of adaptive reuse on a short Old Montreal walk.",
    whatToNotice: ["vaulted banking hall", "ornamental ceiling", "quiet side seating"],
    practicalInfo: ["Good rainy-day stop", "Can be busy during weekday work hours"],
    periodOrStyle: "Beaux-Arts banking hall",
    tags: ["cafes", "architecture", "hidden gems", "rainy day"],
    relatedRouteSlugs: ["churches-courtyards-walk", "place-darmes-circuit"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "st-patricks-basilica",
    slug: "st-patricks-basilica",
    cityId: "montreal",
    name: "St. Patrick's Basilica",
    category: "church",
    area: "Downtown",
    coordinates: { lat: 45.5036, lng: -73.5649 },
    shortDescription: "A Gothic Revival basilica connected to Montreal's Irish community.",
    story: "St. Patrick's adds a downtown heritage thread tied to Montreal's Irish community and Gothic Revival architecture.",
    whyItMatters: "It broadens the religious and immigrant history visible beyond the most familiar Old Montreal landmarks.",
    whatToNotice: ["stone tracery", "interior scale if open", "transition from office district to sanctuary"],
    practicalInfo: ["Verify opening hours before relying on an interior visit", "Sidewalks nearby are generally wide"],
    periodOrStyle: "Gothic Revival",
    tags: ["churches", "history", "architecture"],
    relatedRouteSlugs: ["churches-courtyards-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "mary-queen-cathedral",
    slug: "mary-queen-cathedral",
    cityId: "montreal",
    name: "Mary, Queen of the World Cathedral",
    category: "church",
    area: "Downtown",
    coordinates: { lat: 45.4994, lng: -73.5687 },
    shortDescription: "A downtown cathedral inspired by St. Peter's Basilica in Rome.",
    story: "The cathedral gives downtown a grand religious landmark, showing how Montreal borrowed and reinterpreted European architectural forms.",
    whyItMatters: "It strengthens the architecture and churches theme with a different scale and setting.",
    whatToNotice: ["dome and statues", "urban setback", "contrast with office towers"],
    practicalInfo: ["Nearby traffic is heavier than Old Montreal", "Good transit access"],
    periodOrStyle: "Renaissance Revival",
    tags: ["churches", "architecture", "history"],
    relatedRouteSlugs: ["churches-courtyards-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "mount-royal-chalet",
    slug: "mount-royal-chalet",
    cityId: "montreal",
    name: "Mount Royal Chalet",
    category: "viewpoint",
    area: "Mount Royal",
    coordinates: { lat: 45.5048, lng: -73.5892 },
    shortDescription: "A landmark chalet near one of Montreal's best city views.",
    story: "The chalet makes Mount Royal feel like civic infrastructure as much as parkland, marking the mountain as a shared lookout over the city.",
    whyItMatters: "It anchors Mount Royal discovery with an iconic arrival point and one of the city's clearest skyline reveals.",
    whatToNotice: ["terrace approach", "stone chalet massing", "city view reveal"],
    practicalInfo: ["Expect elevation and some steeper paths", "Best near sunrise or clear late afternoon"],
    tags: ["scenic", "nature", "viewpoints"],
    relatedRouteSlugs: ["mount-royal-sunrise-loop"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "kondiaronk-belvedere",
    slug: "kondiaronk-belvedere",
    cityId: "montreal",
    name: "Kondiaronk Belvedere",
    category: "viewpoint",
    area: "Mount Royal",
    coordinates: { lat: 45.5038, lng: -73.5878 },
    shortDescription: "A broad lookout with sweeping views over downtown Montreal.",
    story: "The belvedere turns the skyline, river, and mountain geography into one legible city-reading moment.",
    whyItMatters: "It is one of the most direct ways to understand Montreal's shape from above.",
    whatToNotice: ["skyline alignment", "river beyond downtown", "morning light across buildings"],
    practicalInfo: ["Can be windy", "Crowds are lighter early"],
    tags: ["scenic", "nature", "photography"],
    relatedRouteSlugs: ["mount-royal-sunrise-loop"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "lachine-canal",
    slug: "lachine-canal",
    cityId: "montreal",
    name: "Lachine Canal",
    category: "waterfront",
    area: "Lachine Canal",
    coordinates: { lat: 45.4828, lng: -73.5757 },
    shortDescription: "A historic industrial canal now used for walking, cycling, and waterfront public space.",
    story: "The canal reframes industrial infrastructure as calm public space and gives Montreal a strong waterfront heritage corridor.",
    whyItMatters: "It connects Montreal's working-waterfront history to present-day neighborhood life and recreation.",
    whatToNotice: ["locks and canal edges", "industrial remnants", "long water views"],
    practicalInfo: ["Shared paths can be busy with bikes", "Wind exposure varies along the water"],
    tags: ["waterfront", "history", "scenic", "accessible"],
    relatedRouteSlugs: ["lachine-canal-heritage-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "atwater-market",
    slug: "atwater-market",
    cityId: "montreal",
    name: "Atwater Market",
    category: "market",
    area: "Saint-Henri",
    coordinates: { lat: 45.4793, lng: -73.5776 },
    shortDescription: "A landmark public market near the canal.",
    story: "Atwater Market gives the canal a food and neighborhood anchor, tying waterfront heritage to everyday shopping and cafe life.",
    whyItMatters: "It adds a practical and sensory landmark to the canal heritage corridor.",
    whatToNotice: ["market tower", "food stalls", "canal-side approach"],
    practicalInfo: ["Good rest and snack stop", "Weekend crowds can slow movement through the market"],
    tags: ["cafes", "food", "waterfront", "architecture"],
    relatedRouteSlugs: ["lachine-canal-heritage-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "habitat-67-viewpoint",
    slug: "habitat-67-viewpoint",
    cityId: "montreal",
    name: "Habitat 67 Viewpoint",
    category: "viewpoint",
    area: "Cite du Havre",
    coordinates: { lat: 45.5001, lng: -73.5433 },
    shortDescription: "A viewpoint toward Moshe Safdie's experimental housing landmark.",
    story: "The view toward Habitat 67 adds a modern architectural chapter to a waterfront area often associated with older stone architecture.",
    whyItMatters: "It makes Montreal's 20th-century architectural ambition visible from the river edge.",
    whatToNotice: ["modular forms", "river setting", "skyline relationship"],
    practicalInfo: ["Longer exposed walk from Old Port", "Best in clear weather"],
    periodOrStyle: "Modernist housing",
    tags: ["architecture", "scenic", "waterfront"],
    relatedRouteSlugs: ["architecture-river-views", "old-port-foundries-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "saint-louis-square",
    slug: "saint-louis-square",
    cityId: "montreal",
    name: "Saint-Louis Square",
    category: "square",
    area: "Plateau",
    coordinates: { lat: 45.5164, lng: -73.5719 },
    shortDescription: "A colorful Plateau square surrounded by Victorian houses and exterior staircases.",
    story: "The square gives the Plateau a concentrated architectural scene and a calmer counterpoint to busier commercial streets.",
    whyItMatters: "It is an accessible visual shorthand for Plateau residential character.",
    whatToNotice: ["painted facades", "spiral staircases", "small park rhythm"],
    practicalInfo: ["Good photo stop", "Residential area requires quiet visitor behavior"],
    tags: ["architecture", "quiet", "hidden gems"],
    relatedRouteSlugs: ["plateau-architecture-cafe-crawl"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "rialto-theatre",
    slug: "rialto-theatre",
    cityId: "montreal",
    name: "Rialto Theatre",
    category: "historic_building",
    area: "Mile End",
    coordinates: { lat: 45.5237, lng: -73.6012 },
    shortDescription: "A historic theater on Parc Avenue with ornate detailing.",
    story: "The Rialto adds theatrical texture to Mile End, showing how neighborhood culture lives in reused landmark buildings.",
    whyItMatters: "It expands the guide beyond Old Montreal into lived neighborhood heritage.",
    whatToNotice: ["theater facade", "vertical sign", "Parc Avenue street life"],
    practicalInfo: ["Check event schedule for interior access", "Sidewalks can be busy near show times"],
    periodOrStyle: "Neo-Baroque theater",
    tags: ["architecture", "history", "hidden gems"],
    relatedRouteSlugs: ["plateau-architecture-cafe-crawl"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "fairmount-bagel-area",
    slug: "fairmount-bagel-area",
    cityId: "montreal",
    name: "Fairmount Bagel Area",
    category: "street",
    area: "Mile End",
    coordinates: { lat: 45.5227, lng: -73.6001 },
    shortDescription: "A Mile End food landmark area near cafes, bakeries, and neighborhood streets.",
    story: "This area turns a simple food stop into a local ritual that feels specific to Montreal.",
    whyItMatters: "It gives Mile End discovery a memorable cafe and food anchor without becoming a generic food list.",
    whatToNotice: ["bakery storefront rhythm", "side-street scale", "nearby cafe cluster"],
    practicalInfo: ["Expect lines at peak times", "Good snack stop before continuing"],
    tags: ["cafes", "food", "hidden gems"],
    relatedRouteSlugs: ["plateau-architecture-cafe-crawl"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "la-fontaine-park",
    slug: "la-fontaine-park",
    cityId: "montreal",
    name: "La Fontaine Park",
    category: "park",
    area: "Plateau",
    coordinates: { lat: 45.5272, lng: -73.5697 },
    shortDescription: "A large Plateau park with ponds, paths, and neighborhood edges.",
    story: "The park gives Plateau discovery breathing room and offers a softer, nature-heavy option within the same urban guide.",
    whyItMatters: "It supports quiet and family-friendly searches without leaving the city.",
    whatToNotice: ["pond edges", "tree canopy", "neighborhood approaches"],
    practicalInfo: ["Paths vary by season", "Good option for families and slower walks"],
    tags: ["nature", "quiet", "family-friendly", "parks"],
    relatedRouteSlugs: ["plateau-architecture-cafe-crawl"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "mcgill-arts-building",
    slug: "mcgill-arts-building",
    cityId: "montreal",
    name: "McGill Arts Building",
    category: "historic_building",
    area: "Downtown",
    coordinates: { lat: 45.5048, lng: -73.5772 },
    shortDescription: "A classical campus landmark at the heart of McGill University.",
    story: "The building adds an academic and institutional layer to downtown architecture discovery.",
    whyItMatters: "It broadens architectural discovery beyond tourist-heavy Old Montreal.",
    whatToNotice: ["central portico", "campus axis", "relationship to Mount Royal"],
    practicalInfo: ["Campus paths are generally walkable", "Respect university operations"],
    periodOrStyle: "Classical Revival",
    tags: ["architecture", "history", "quiet"],
    relatedRouteSlugs: ["architecture-river-views"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "redpath-museum",
    slug: "redpath-museum",
    cityId: "montreal",
    name: "Redpath Museum",
    category: "museum",
    area: "Downtown",
    coordinates: { lat: 45.5042, lng: -73.5778 },
    shortDescription: "A compact natural history museum on the McGill campus.",
    story: "The museum gives downtown discovery a small, curious, rainy-day stop that can fit inside a short route.",
    whyItMatters: "It supports hidden-gem and rainy-day searches while staying walkable.",
    whatToNotice: ["museum facade", "campus setting", "small-scale institutional detail"],
    practicalInfo: ["Check opening hours before visiting", "Good indoor backup"],
    tags: ["museums", "hidden gems", "rainy day"],
    relatedRouteSlugs: ["architecture-river-views"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "old-port-clock-tower",
    slug: "old-port-clock-tower",
    cityId: "montreal",
    name: "Old Port Clock Tower",
    category: "historic_building",
    area: "Old Port",
    coordinates: { lat: 45.5122, lng: -73.5492 },
    shortDescription: "A waterfront clock tower and landmark at the eastern edge of the Old Port.",
    story: "The clock tower marks a ceremonial edge of the port, turning harbor infrastructure into a public orientation point.",
    whyItMatters: "It gives the riverfront a visible eastern anchor and a strong skyline marker.",
    whatToNotice: ["tower silhouette", "river exposure", "views back toward Old Montreal"],
    practicalInfo: ["Wind can be stronger by the water", "Best paired with Old Port paths"],
    periodOrStyle: "Early 20th-century port landmark",
    tags: ["waterfront", "history", "scenic", "architecture"],
    relatedRouteSlugs: ["old-port-foundries-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "quays-of-old-port",
    slug: "quays-of-old-port",
    cityId: "montreal",
    name: "Quays of the Old Port",
    category: "waterfront",
    area: "Old Port",
    coordinates: { lat: 45.5059, lng: -73.5508 },
    shortDescription: "A broad riverfront zone with long views and public gathering spaces.",
    story: "The quays show how former port edges have become civic public space without losing the sense of the river's working scale.",
    whyItMatters: "They connect Old Montreal landmarks to the St. Lawrence and make the river part of the city story.",
    whatToNotice: ["river scale", "warehouse edges", "skyline views"],
    practicalInfo: ["Shared pedestrian and cycling areas can be busy", "Use in clear weather for best views"],
    tags: ["waterfront", "scenic", "family-friendly"],
    relatedRouteSlugs: ["old-port-foundries-walk", "architecture-river-views"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "champ-de-mars",
    slug: "champ-de-mars",
    cityId: "montreal",
    name: "Champ-de-Mars",
    category: "park",
    area: "Old Montreal",
    coordinates: { lat: 45.5103, lng: -73.5554 },
    shortDescription: "A green civic space with traces of Montreal's old fortifications.",
    story: "Champ-de-Mars gives the old city a quieter pause while keeping civic and defensive history close to the surface.",
    whyItMatters: "It adds a quieter heritage stop for walkers who want history beyond the most familiar landmark facades.",
    whatToNotice: ["open lawn", "civic building edges", "fortification traces"],
    practicalInfo: ["Good reset stop near City Hall", "Check paths after winter thaw"],
    tags: ["history", "parks", "quiet"],
    relatedRouteSlugs: ["old-montreal-monuments-loop"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "victoria-square",
    slug: "victoria-square",
    cityId: "montreal",
    name: "Victoria Square",
    category: "square",
    area: "Downtown",
    coordinates: { lat: 45.5014, lng: -73.5616 },
    shortDescription: "A downtown square linking Old Montreal, the international district, and transit history.",
    story: "Victoria Square is a hinge between old stone streets and the modern business district, with transit and public art cues at street level.",
    whyItMatters: "It helps users read the transition from heritage streets to institutional and business-district architecture.",
    whatToNotice: ["metro entrance", "tree canopy", "office district edges"],
    practicalInfo: ["Busy at commute times", "Useful downtown meeting point"],
    tags: ["architecture", "history", "square"],
    relatedRouteSlugs: ["architecture-river-views", "churches-courtyards-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "dorchester-square",
    slug: "dorchester-square",
    cityId: "montreal",
    name: "Dorchester Square",
    category: "square",
    area: "Downtown",
    coordinates: { lat: 45.499, lng: -73.5711 },
    shortDescription: "A formal downtown square framed by major civic, hotel, and church landmarks.",
    story: "The square reads as a civic room, where religious, railway, and commercial histories meet in a compact downtown setting.",
    whyItMatters: "It strengthens downtown architecture discovery with a clear public-space anchor.",
    whatToNotice: ["formal paths", "nearby cathedral dome", "hotel and office facades"],
    practicalInfo: ["Good pause before or after Mary, Queen of the World", "Traffic is heavy on nearby streets"],
    tags: ["architecture", "history", "square", "quiet"],
    relatedRouteSlugs: ["churches-courtyards-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "smith-house-mount-royal",
    slug: "smith-house-mount-royal",
    cityId: "montreal",
    name: "Smith House",
    category: "historic_building",
    area: "Mount Royal",
    coordinates: { lat: 45.5085, lng: -73.5879 },
    shortDescription: "A Mount Royal park building and practical orientation stop near trail junctions.",
    story: "Smith House makes the mountain feel navigable, giving visitors a built landmark before the park becomes more wooded.",
    whyItMatters: "It gives Mount Royal discovery a real midpoint, rest cue, and orientation point.",
    whatToNotice: ["stone building", "trail junctions", "park information points"],
    practicalInfo: ["Useful rest and orientation point", "Path grades vary nearby"],
    tags: ["nature", "history", "quiet"],
    relatedRouteSlugs: ["mount-royal-sunrise-loop"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "beaver-lake",
    slug: "beaver-lake",
    cityId: "montreal",
    name: "Beaver Lake",
    category: "park",
    area: "Mount Royal",
    coordinates: { lat: 45.4969, lng: -73.596 },
    shortDescription: "A calm lake and park node on Mount Royal with a slower, nature-forward rhythm.",
    story: "Beaver Lake adds a softer park chapter to the skyline-focused mountain experience.",
    whyItMatters: "It shows Mount Royal as a park landscape, not only a climb to one viewpoint.",
    whatToNotice: ["lake edge", "tree canopy", "seasonal activity"],
    practicalInfo: ["Some paths are sloped", "Seasonal conditions can change quickly"],
    tags: ["nature", "quiet", "family-friendly", "scenic"],
    relatedRouteSlugs: ["mount-royal-sunrise-loop"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "saint-gabriel-locks",
    slug: "saint-gabriel-locks",
    cityId: "montreal",
    name: "Saint-Gabriel Locks",
    category: "waterfront",
    area: "Lachine Canal",
    coordinates: { lat: 45.4806, lng: -73.5656 },
    shortDescription: "Historic canal locks that make the industrial waterway legible up close.",
    story: "The locks are a practical piece of infrastructure that helps explain why the canal mattered to Montreal's industrial growth.",
    whyItMatters: "They add a concrete heritage stop to the canal beyond long waterfront views.",
    whatToNotice: ["lock gates", "canal level changes", "path and bridge crossings"],
    practicalInfo: ["Stay aware of cyclists on shared paths", "Best in daylight for reading the infrastructure"],
    tags: ["waterfront", "history", "scenic"],
    relatedRouteSlugs: ["lachine-canal-heritage-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "maison-saint-gabriel",
    slug: "maison-saint-gabriel",
    cityId: "montreal",
    name: "Maison Saint-Gabriel",
    category: "museum",
    area: "Pointe-Saint-Charles",
    coordinates: { lat: 45.4757, lng: -73.5568 },
    shortDescription: "A historic house museum near the canal corridor.",
    story: "This stop broadens the canal story from industry to settlement, land, and everyday heritage.",
    whyItMatters: "It gives the canal corridor a substantial cultural stop near the western edge of the Montreal guide area.",
    whatToNotice: ["stone house massing", "garden setting", "relationship to canal-side neighborhoods"],
    practicalInfo: ["Check hours before planning an interior visit", "Longer detour from the main canal path"],
    periodOrStyle: "17th-century rural stone house",
    tags: ["history", "museums", "hidden gems"],
    relatedRouteSlugs: ["lachine-canal-heritage-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "jean-talon-market",
    slug: "jean-talon-market",
    cityId: "montreal",
    name: "Jean-Talon Market",
    category: "market",
    area: "Little Italy",
    coordinates: { lat: 45.5351, lng: -73.6147 },
    shortDescription: "A major public market and neighborhood food destination.",
    story: "The market is one of Montreal's clearest everyday food landmarks, where neighborhood shopping, seasonal produce, and cafe life spill into the surrounding streets.",
    whyItMatters: "It shows Montreal as a lived-in food city, not just a set of historic monuments.",
    whatToNotice: ["market aisles", "seasonal produce", "neighborhood cafe edges"],
    practicalInfo: ["Busy on weekends", "Best early if you want a calmer market visit"],
    tags: ["food", "cafes", "market", "family-friendly"],
    relatedRouteSlugs: [],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "place-ville-marie-ring",
    slug: "place-ville-marie-ring",
    cityId: "montreal",
    name: "The Ring at Place Ville Marie",
    category: "public_art",
    area: "Downtown",
    coordinates: { lat: 45.5019, lng: -73.5682 },
    shortDescription: "A large public artwork framing a downtown view toward Mount Royal.",
    story: "The Ring gives downtown Montreal a simple visual orientation device: stand under it and the city axis toward the mountain becomes part of the artwork.",
    whyItMatters: "It gives public-art discovery an immediate landmark and a strong photo-oriented starting point.",
    whatToNotice: ["the mountain view through the ring", "office-tower scale", "how pedestrians use the plaza"],
    practicalInfo: ["Best in clear weather", "Useful meeting point near transit and office towers"],
    periodOrStyle: "Contemporary public art",
    tags: ["public art", "architecture", "scenic", "downtown"],
    relatedRouteSlugs: ["public-art-downtown-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "place-des-arts",
    slug: "place-des-arts",
    cityId: "montreal",
    name: "Place des Arts",
    category: "public_square",
    area: "Quartier des spectacles",
    coordinates: { lat: 45.5087, lng: -73.5665 },
    shortDescription: "A major cultural plaza and performance complex in central Montreal.",
    story: "Place des Arts concentrates the city's festival, performance, and public-square energy into one walkable downtown node.",
    whyItMatters: "It anchors public-art and cultural discovery with a reliable open space.",
    whatToNotice: ["plaza scale", "performance entrances", "night lighting and festival infrastructure"],
    practicalInfo: ["Busy during events", "Good transit access from Place-des-Arts station"],
    tags: ["public art", "architecture", "public square", "downtown"],
    relatedRouteSlugs: ["public-art-downtown-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "illuminated-crowd",
    slug: "illuminated-crowd",
    cityId: "montreal",
    name: "The Illuminated Crowd",
    category: "public_art",
    area: "Downtown",
    coordinates: { lat: 45.5018, lng: -73.5707 },
    shortDescription: "A well-known sculptural group outside a downtown office tower.",
    story: "The sculpture gives a short downtown walk a human-scale pause between office towers, shopping corridors, and museum streets.",
    whyItMatters: "It helps the catalog support public-art searches without needing a new visual language.",
    whatToNotice: ["the crowd composition", "how the figures face the street", "the surrounding office plaza"],
    practicalInfo: ["Exterior stop only", "Sidewalks can be busy at lunch and commute times"],
    periodOrStyle: "Contemporary sculpture",
    tags: ["public art", "downtown", "architecture"],
    relatedRouteSlugs: ["public-art-downtown-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "mccord-stewart-museum",
    slug: "mccord-stewart-museum",
    cityId: "montreal",
    name: "McCord Stewart Museum",
    category: "museum",
    area: "Downtown",
    coordinates: { lat: 45.5035, lng: -73.5734 },
    shortDescription: "A museum near McGill focused on Montreal, Quebec, and Canadian history and culture.",
    story: "The museum bridges campus, downtown, and city-history themes, making it useful for visitors who want culture beyond architecture alone.",
    whyItMatters: "It gives museum and campus discovery a strong indoor cultural anchor.",
    whatToNotice: ["campus edge", "Sherbrooke Street frontage", "museum banners and public entry"],
    practicalInfo: ["Check hours before planning an interior visit", "Good rainy-day option"],
    tags: ["museums", "history", "campus", "rainy day"],
    relatedRouteSlugs: ["museums-campus-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "montreal-museum-fine-arts",
    slug: "montreal-museum-fine-arts",
    cityId: "montreal",
    name: "Montreal Museum of Fine Arts",
    category: "museum",
    area: "Golden Square Mile",
    coordinates: { lat: 45.4986, lng: -73.5793 },
    shortDescription: "A major art museum spread across several pavilions on Sherbrooke Street.",
    story: "The museum turns Sherbrooke Street into a cultural spine where galleries, older mansions, and contemporary museum architecture meet.",
    whyItMatters: "It gives the guide a high-confidence museum anchor for longer downtown exploration.",
    whatToNotice: ["museum pavilions", "Sherbrooke Street facades", "public sculpture and entry sequence"],
    practicalInfo: ["Interior visits need more time than a quick stop", "Nearby streets include slopes"],
    tags: ["museums", "architecture", "rainy day", "downtown"],
    relatedRouteSlugs: ["museums-campus-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "roddick-gates",
    slug: "roddick-gates",
    cityId: "montreal",
    name: "Roddick Gates",
    category: "campus",
    area: "McGill",
    coordinates: { lat: 45.504, lng: -73.576 },
    shortDescription: "The formal Sherbrooke Street entrance to McGill University's downtown campus.",
    story: "The gates mark a clean transition from commercial downtown into a quieter campus landscape at the foot of Mount Royal.",
    whyItMatters: "They make the downtown campus legible and give visitors a clear orientation point.",
    whatToNotice: ["gate alignment", "campus axis", "view toward Mount Royal"],
    practicalInfo: ["Respect campus operations", "Paths are generally walkable but busy between classes"],
    tags: ["campus", "architecture", "quiet", "downtown"],
    relatedRouteSlugs: ["museums-campus-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "phillips-square",
    slug: "phillips-square",
    cityId: "montreal",
    name: "Phillips Square",
    category: "public_square",
    area: "Downtown",
    coordinates: { lat: 45.5034, lng: -73.5687 },
    shortDescription: "A compact downtown square surrounded by retail, offices, and older facades.",
    story: "Phillips Square is a useful quieter room inside the downtown grid, where small-scale public space interrupts heavier commercial streets.",
    whyItMatters: "It gives downtown a small public pause between heavier commercial streets.",
    whatToNotice: ["tree canopy", "street crossings", "historic retail edges"],
    practicalInfo: ["Good pause point", "Traffic and construction patterns can change around the square"],
    tags: ["public square", "quiet", "architecture", "downtown"],
    relatedRouteSlugs: ["hidden-squares-quiet-streets", "public-art-downtown-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "square-saint-henri",
    slug: "square-saint-henri",
    cityId: "montreal",
    name: "Square Saint-Henri",
    category: "public_square",
    area: "Saint-Henri",
    coordinates: { lat: 45.4772, lng: -73.5863 },
    shortDescription: "A neighborhood square close to Saint-Henri streets and the canal.",
    story: "The square gives western neighborhood discovery a calm civic pause near market and canal segments.",
    whyItMatters: "It brings food, neighborhood, and civic public-space discovery beyond the tourist core.",
    whatToNotice: ["local street rhythm", "mature trees", "connections toward the canal"],
    practicalInfo: ["Best as a rest stop", "Check winter path conditions"],
    tags: ["public square", "quiet", "neighborhood", "food"],
    relatedRouteSlugs: ["markets-neighborhood-food-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "dante-park",
    slug: "dante-park",
    cityId: "montreal",
    name: "Dante Park",
    category: "park",
    area: "Little Italy",
    coordinates: { lat: 45.5325, lng: -73.611 },
    shortDescription: "A small Little Italy park near market streets and community landmarks.",
    story: "Dante Park makes Little Italy feel like a neighborhood, not just a sequence of shops.",
    whyItMatters: "It gives market-area discovery a quiet public-space stop near Little Italy landmarks.",
    whatToNotice: ["park scale", "church and residential edges", "local cafe rhythm"],
    practicalInfo: ["Good pause point near Jean-Talon Market", "Residential streets nearby call for quiet visitor behavior"],
    tags: ["parks", "food", "quiet", "family-friendly"],
    relatedRouteSlugs: ["markets-neighborhood-food-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "madonna-della-difesa",
    slug: "madonna-della-difesa",
    cityId: "montreal",
    name: "Church of Madonna della Difesa",
    category: "church",
    area: "Little Italy",
    coordinates: { lat: 45.5324, lng: -73.6116 },
    shortDescription: "A Little Italy church that adds cultural history near the market area.",
    story: "The church helps explain Little Italy as a community landscape rather than only a food destination.",
    whyItMatters: "It adds heritage depth to the market and surrounding neighborhood.",
    whatToNotice: ["church facade", "park relationship", "community-scale streets"],
    practicalInfo: ["Check access before planning an interior stop", "Exterior viewing is easy from nearby sidewalks"],
    tags: ["churches", "history", "food", "architecture"],
    relatedRouteSlugs: ["markets-neighborhood-food-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "little-italy-saint-laurent",
    slug: "little-italy-saint-laurent",
    cityId: "montreal",
    name: "Little Italy Saint-Laurent Strip",
    category: "street",
    area: "Little Italy",
    coordinates: { lat: 45.5337, lng: -73.613 },
    shortDescription: "A food-oriented neighborhood street segment near Jean-Talon Market.",
    story: "This stop keeps food discovery grounded in street life, storefronts, and real neighborhood movement.",
    whyItMatters: "It gives food, cafe, and neighborhood searches a real place to match.",
    whatToNotice: ["storefront rhythm", "cafe patios", "market approach streets"],
    practicalInfo: ["Sidewalks can be crowded on market days", "Best understood as a street segment rather than a single destination"],
    tags: ["food", "cafes", "neighborhood", "old streets"],
    relatedRouteSlugs: ["markets-neighborhood-food-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "plaza-st-hubert",
    slug: "plaza-st-hubert",
    cityId: "montreal",
    name: "Plaza St-Hubert",
    category: "market",
    area: "Rosemont",
    coordinates: { lat: 45.539, lng: -73.607 },
    shortDescription: "A covered commercial street with neighborhood shops and food stops.",
    story: "Plaza St-Hubert gives food discovery a different retail texture from open-air markets and cafe corners.",
    whyItMatters: "It broadens neighborhood food discovery without adding marketplace features.",
    whatToNotice: ["covered sidewalk rhythm", "shop signs", "local food stops"],
    practicalInfo: ["Best during business hours", "Check current construction before planning around the street"],
    tags: ["food", "market", "cafes", "rainy day"],
    relatedRouteSlugs: ["markets-neighborhood-food-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "marche-maisonneuve",
    slug: "marche-maisonneuve",
    cityId: "montreal",
    name: "Maisonneuve Market",
    category: "market",
    area: "Hochelaga-Maisonneuve",
    coordinates: { lat: 45.5536, lng: -73.539 },
    shortDescription: "A neighborhood public market in Montreal's east end.",
    story: "The market extends Montreal discovery eastward while keeping the catalog grounded in real neighborhood anchors.",
    whyItMatters: "It helps the place catalog reach beyond central tourist stops.",
    whatToNotice: ["market building", "local vendor rhythm", "nearby residential streets"],
    practicalInfo: ["Best during market hours", "Longer transit connection from the current central cluster"],
    tags: ["market", "food", "neighborhood", "family-friendly"],
    relatedRouteSlugs: [],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "botanical-garden-entrance",
    slug: "botanical-garden-entrance",
    cityId: "montreal",
    name: "Botanical Garden Entrance",
    category: "park",
    area: "Olympic Park",
    coordinates: { lat: 45.5585, lng: -73.554 },
    shortDescription: "The main gateway toward Montreal's botanical garden landscape.",
    story: "The garden entrance marks the transition from Olympic Park scale to one of Montreal's most recognizable landscaped institutions.",
    whyItMatters: "It gives families and nature-focused visitors a clear east-end landmark to orient around.",
    whatToNotice: ["entry landscape", "garden edges", "nearby Olympic Park views"],
    practicalInfo: ["Interior access may require admission", "Use as an exterior orientation point unless tickets are planned separately"],
    tags: ["parks", "nature", "family-friendly", "scenic"],
    relatedRouteSlugs: [],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "jean-drapeau-river-view",
    slug: "jean-drapeau-river-view",
    cityId: "montreal",
    name: "Parc Jean-Drapeau River View",
    category: "viewpoint",
    area: "Parc Jean-Drapeau",
    coordinates: { lat: 45.5151, lng: -73.5338 },
    shortDescription: "A river and skyline viewpoint from the islands east of downtown.",
    story: "The viewpoint puts the skyline across the water, turning the islands into one of the clearest ways to read Montreal's shape from outside downtown.",
    whyItMatters: "It offers a river-level counterpoint to the mountain and Old Montreal viewpoints.",
    whatToNotice: ["skyline across the river", "island paths", "bridge and water views"],
    practicalInfo: ["Wind and event closures can affect access", "Check transit and path status before routing"],
    tags: ["scenic", "viewpoints", "waterfront", "parks"],
    relatedRouteSlugs: [],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "quartier-des-spectacles",
    slug: "quartier-des-spectacles",
    cityId: "montreal",
    name: "Quartier des spectacles",
    category: "public_square",
    area: "Quartier des spectacles",
    coordinates: { lat: 45.5094, lng: -73.5637 },
    shortDescription: "A downtown cultural district with plazas, lights, festivals, and public art.",
    story: "The district makes public space feel programmable: light, performance, and temporary installations change the experience by time of day.",
    whyItMatters: "It is essential for public-art and evening downtown discovery.",
    whatToNotice: ["festival infrastructure", "lighting masts", "plaza-to-street transitions"],
    practicalInfo: ["Check event closures", "Evening visits are more visually active"],
    tags: ["public art", "public square", "downtown", "scenic"],
    relatedRouteSlugs: ["public-art-downtown-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "place-de-la-dauversiere",
    slug: "place-de-la-dauversiere",
    cityId: "montreal",
    name: "Place de la Dauversiere",
    category: "public_square",
    area: "Old Montreal",
    coordinates: { lat: 45.508, lng: -73.5547 },
    shortDescription: "A small civic square near City Hall and Champ-de-Mars.",
    story: "The square provides a quieter Old Montreal pause between more visible civic landmarks.",
    whyItMatters: "It supports hidden-square discovery without inventing new attractions.",
    whatToNotice: ["civic edges", "short sightlines to City Hall", "quieter seating moments"],
    practicalInfo: ["Good short pause", "Nearby sidewalks can be affected by civic events"],
    tags: ["public square", "quiet", "history", "old streets"],
    relatedRouteSlugs: ["hidden-squares-quiet-streets"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "cours-le-royer",
    slug: "cours-le-royer",
    cityId: "montreal",
    name: "Cours Le Royer",
    category: "hidden_gem",
    area: "Old Montreal",
    coordinates: { lat: 45.503, lng: -73.5552 },
    shortDescription: "A tucked-away Old Montreal courtyard sequence close to major landmarks.",
    story: "Cours Le Royer shifts the old-city walk from landmark facades to more intimate stone passages and quieter thresholds.",
    whyItMatters: "It gives hidden-gem search results a credible central stop.",
    whatToNotice: ["stone courtyard scale", "passage rhythm", "contrast with busier nearby streets"],
    practicalInfo: ["Respect private entries and posted access", "Best visited quietly in daylight"],
    tags: ["hidden gems", "quiet", "architecture", "old streets"],
    relatedRouteSlugs: ["hidden-squares-quiet-streets"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "grand-seminaire-montreal",
    slug: "grand-seminaire-montreal",
    cityId: "montreal",
    name: "Grand Seminaire de Montreal",
    category: "heritage_building",
    area: "Downtown",
    coordinates: { lat: 45.4949, lng: -73.5827 },
    shortDescription: "A historic institutional complex west of downtown's main museum corridor.",
    story: "The seminary adds a quieter institutional chapter to downtown architecture discovery.",
    whyItMatters: "It helps museum and campus discovery move beyond the McGill-only cluster.",
    whatToNotice: ["stone institutional frontage", "setback from busy streets", "garden and wall edges"],
    practicalInfo: ["Exterior viewing only unless access is confirmed", "Nearby streets include moderate slopes"],
    periodOrStyle: "Historic institutional architecture",
    tags: ["heritage", "architecture", "quiet", "churches"],
    relatedRouteSlugs: ["museums-campus-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "concordia-ev-building",
    slug: "concordia-ev-building",
    cityId: "montreal",
    name: "Concordia EV Building",
    category: "campus",
    area: "Downtown",
    coordinates: { lat: 45.4955, lng: -73.5785 },
    shortDescription: "A contemporary university building near Montreal's museum corridor.",
    story: "The EV Building adds a modern campus note between Sherbrooke Street museums and downtown institutional streets.",
    whyItMatters: "It broadens campus discovery beyond McGill while staying close to the museum corridor.",
    whatToNotice: ["glass facade", "student street life", "contrast with older museum buildings"],
    practicalInfo: ["Exterior stop only by default", "Sidewalks are busy during class changes"],
    tags: ["campus", "architecture", "downtown"],
    relatedRouteSlugs: ["museums-campus-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "canadian-centre-architecture",
    slug: "canadian-centre-architecture",
    cityId: "montreal",
    name: "Canadian Centre for Architecture",
    category: "museum",
    area: "Shaughnessy Village",
    coordinates: { lat: 45.4915, lng: -73.578 },
    shortDescription: "An architecture museum and garden campus near downtown.",
    story: "The centre makes architecture itself the subject, connecting museum culture with urban design.",
    whyItMatters: "It is a natural endpoint for architecture and museum searches.",
    whatToNotice: ["garden edge", "museum massing", "relationship between older house and newer additions"],
    practicalInfo: ["Check hours for interior visits", "Good exterior stop even without entering"],
    tags: ["museums", "architecture", "campus", "quiet"],
    relatedRouteSlugs: ["museums-campus-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "laurier-park",
    slug: "laurier-park",
    cityId: "montreal",
    name: "Laurier Park",
    category: "park",
    area: "Plateau",
    coordinates: { lat: 45.5327, lng: -73.5895 },
    shortDescription: "A neighborhood park that extends Plateau discovery northward.",
    story: "Laurier Park gives the Plateau a more local, slower endpoint than the best-known facade streets.",
    whyItMatters: "It supports quiet and family-friendly searches in a neighborhood people actually walk.",
    whatToNotice: ["tree canopy", "local park use", "residential edges"],
    practicalInfo: ["Good rest stop", "Seasonal path conditions vary"],
    tags: ["parks", "quiet", "family-friendly", "nature"],
    relatedRouteSlugs: [],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "st-viateur-bagel-area",
    slug: "st-viateur-bagel-area",
    cityId: "montreal",
    name: "St-Viateur Bagel Area",
    category: "cafe_adjacent_stop",
    area: "Mile End",
    coordinates: { lat: 45.5229, lng: -73.6018 },
    shortDescription: "A Mile End food stop near cafes, bakeries, and residential side streets.",
    story: "The stop represents the kind of small food ritual that makes Mile End feel local: a quick line, a familiar storefront, and residential side streets nearby.",
    whyItMatters: "It anchors food discovery in a neighborhood rhythm rather than a generic restaurant list.",
    whatToNotice: ["bakery storefront", "side-street rhythm", "nearby cafe corners"],
    practicalInfo: ["Expect lines at peak times", "Good snack stop rather than a long break"],
    tags: ["food", "cafes", "hidden gems", "neighborhood"],
    relatedRouteSlugs: ["markets-neighborhood-food-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "sun-yat-sen-park",
    slug: "sun-yat-sen-park",
    cityId: "montreal",
    name: "Sun Yat-sen Park",
    category: "park",
    area: "Chinatown",
    coordinates: { lat: 45.5085, lng: -73.5607 },
    shortDescription: "A small Chinatown park close to downtown and Old Montreal.",
    story: "The park gives central discovery a compact neighborhood pause between Old Montreal and downtown.",
    whyItMatters: "It adds a quieter civic stop near high-traffic visitor corridors.",
    whatToNotice: ["park scale", "gateway streets", "restaurant and community edges"],
    practicalInfo: ["Best as a short stop", "Nearby sidewalks can be crowded during meal times"],
    tags: ["parks", "food", "quiet", "downtown"],
    relatedRouteSlugs: ["hidden-squares-quiet-streets"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "chinatown-paifang",
    slug: "chinatown-paifang",
    cityId: "montreal",
    name: "Chinatown Paifang",
    category: "architecture",
    area: "Chinatown",
    coordinates: { lat: 45.5075, lng: -73.5608 },
    shortDescription: "A gateway marker for Montreal's Chinatown streets.",
    story: "The gateway helps users orient themselves between downtown, Chinatown, and Old Montreal.",
    whyItMatters: "It supports architecture and food-neighborhood searches with a visible street marker.",
    whatToNotice: ["gateway details", "street framing", "nearby restaurants and shops"],
    practicalInfo: ["Exterior stop only", "Use crosswalks carefully on nearby streets"],
    tags: ["architecture", "food", "public art", "downtown"],
    relatedRouteSlugs: ["hidden-squares-quiet-streets"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "cabot-square",
    slug: "cabot-square",
    cityId: "montreal",
    name: "Cabot Square",
    category: "public_square",
    area: "Downtown West",
    coordinates: { lat: 45.4899, lng: -73.5845 },
    shortDescription: "A downtown west public square near transit, hospitals, and museum-area streets.",
    story: "Cabot Square adds a real public-space endpoint west of the main downtown core.",
    whyItMatters: "It broadens hidden-square coverage beyond Old Montreal and the Plateau.",
    whatToNotice: ["public seating", "transit activity", "edges between institutions and residences"],
    practicalInfo: ["Busy transit node", "Use normal urban awareness after dark"],
    tags: ["public square", "downtown", "quiet", "architecture"],
    relatedRouteSlugs: [],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "saint-joseph-oratory",
    slug: "saint-joseph-oratory",
    cityId: "montreal",
    name: "Saint Joseph's Oratory",
    category: "church",
    area: "Cote-des-Neiges",
    coordinates: { lat: 45.4911, lng: -73.6164 },
    shortDescription: "A major basilica and hilltop landmark west of Mount Royal.",
    story: "The oratory is one of Montreal's most visible hilltop landmarks, combining pilgrimage, monumental architecture, and wide views over the west side of the city.",
    whyItMatters: "It is a high-recognition spiritual and architectural place, even outside the first central discovery cluster.",
    whatToNotice: ["large dome", "steps and terraces", "views from the hill"],
    practicalInfo: ["Elevation and stairs are significant", "Check accessible paths before visiting"],
    periodOrStyle: "Basilica and pilgrimage architecture",
    tags: ["churches", "architecture", "viewpoints", "history"],
    relatedRouteSlugs: [],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "georges-etienne-cartier-monument",
    slug: "georges-etienne-cartier-monument",
    cityId: "montreal",
    name: "George-Etienne Cartier Monument",
    category: "monument",
    area: "Mount Royal",
    coordinates: { lat: 45.5145, lng: -73.585 },
    shortDescription: "A major monument at the edge of Mount Royal Park.",
    story: "The monument creates a civic threshold between parkland and Plateau street life.",
    whyItMatters: "It strengthens monument, park, and Mount Royal discovery beyond viewpoint-only visits.",
    whatToNotice: ["monument scale", "park edge", "Avenue du Parc movement"],
    practicalInfo: ["Busy nearby road crossings", "Good daylight stop before entering park paths"],
    tags: ["monuments", "parks", "history", "architecture"],
    relatedRouteSlugs: [],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "belgo-building",
    slug: "belgo-building",
    cityId: "montreal",
    name: "Belgo Building",
    category: "heritage_building",
    area: "Downtown",
    coordinates: { lat: 45.505, lng: -73.5685 },
    shortDescription: "A downtown building known for galleries and creative reuse.",
    story: "The Belgo Building gives public-art discovery an indoor-adjacent cultural stop without requiring ticketing or a gallery schedule.",
    whyItMatters: "It connects street-level public art to Montreal's gallery ecosystem.",
    whatToNotice: ["older commercial facade", "gallery listings", "creative reuse cues"],
    practicalInfo: ["Interior access and gallery hours vary", "Use as an exterior/cultural context stop by default"],
    tags: ["public art", "architecture", "hidden gems", "rainy day"],
    relatedRouteSlugs: ["public-art-downtown-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  },
  {
    id: "place-jean-riopelle",
    slug: "place-jean-riopelle",
    cityId: "montreal",
    name: "Place Jean-Riopelle",
    category: "public_square",
    area: "International District",
    coordinates: { lat: 45.5023, lng: -73.56 },
    shortDescription: "A public square in the international district with a strong art-and-office context.",
    story: "The square links downtown business streets with a more deliberate public-art rhythm.",
    whyItMatters: "It gives public-art discovery a central bridge between Old Montreal and downtown.",
    whatToNotice: ["square geometry", "public art setting", "office and convention-center edges"],
    practicalInfo: ["Good weekday pause", "Nearby event traffic can change the feel quickly"],
    tags: ["public art", "public square", "architecture", "downtown"],
    relatedRouteSlugs: ["public-art-downtown-walk"],
    sourceQuality: "draft",
    lastReviewedAt: "2026-07-01"
  }
];

export const places: Place[] = basePlaces.map(withPlaceDefaults);

export function getPlaceById(placeId: string): Place | undefined {
  return places.find((place) => place.id === placeId);
}

export function getPlaceBySlug(slug: string): Place | undefined {
  return places.find((place) => place.slug === slug);
}

function withPlaceDefaults(place: PlaceInput): Place {
  const media = getMediaAssetsForPlace(place.id);

  return {
    ...place,
    sources: [sourcePlaceholder],
    media: [
      ...media,
      createGeneratedFallbackMedia({
        id: `${place.slug}-generated-fallback`,
        alt: `${place.name} generated local visual fallback.`,
        title: `${place.name} fallback visual`
      })
    ],
    contentStatus: "ready",
    accessibilityNotes: defaultAccessibilityNotes,
    safetyNotes: defaultSafetyNotes
  };
}
