export const stitchTokens = {
  color: {
    background: '#f9f9fc',
    surface: '#f9f9fc',
    surfaceDim: '#dadadc',
    surfaceBright: '#f9f9fc',
    surfaceLowest: '#ffffff',
    surfaceLow: '#f3f3f6',
    surfaceContainer: '#eeeef0',
    surfaceHigh: '#e8e8ea',
    surfaceHighest: '#e2e2e5',
    text: '#1a1c1e',
    muted: '#58423c',
    outline: '#8b716a',
    outlineVariant: '#dfc0b7',
    primary: '#a43716',
    primaryContainer: '#c54f2c',
    primarySoft: '#ffdbd1',
    primarySoftDim: '#ffb5a0',
    secondary: '#3c6840',
    secondaryContainer: '#baecba',
    secondarySoft: '#bdefbd',
    tertiary: '#615b51',
    tertiaryContainer: '#7a7469',
    error: '#ba1a1a',
    onPrimary: '#ffffff',
    onSecondary: '#ffffff',
  },
  font: {
    headline: 'Hanken Grotesk',
    body: 'Public Sans',
  },
  radius: {
    small: '2px',
    standard: '4px',
    medium: '6px',
    large: '8px',
    xl: '12px',
    pill: '9999px',
  },
  spacing: {
    unit: '8px',
    containerMargin: '20px',
    gutter: '16px',
    stackSmall: '8px',
    stackMedium: '16px',
    stackLarge: '32px',
  },
} as const;

export type StitchTokenSet = typeof stitchTokens;
